// Copyright (c) 2022 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//   IBM Corporation
:projectid: microprofile-config-profile
:page-layout: guide-multipane
:page-duration: 30 minutes
:page-releasedate: 2022-12-09
:page-description: Explore how to externalize configuration using MicroProfile Config and configure microservices for different environments with MicroProfile Config Profile.
:page-tags: ['MicroProfile']
:page-permalink: /guides/{projectid}
:page-related-guides: ['microprofile-config-intro']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/prod
:source-highlighter: prettify
:page-seo-title: Configuring microservices for different environments with MicroProfile Config Profile
:page-seo-description: A tutorial and example on how to externalize configuration properties and configure multiple development stages for Java microservices using Eclipse MicroProfile Config.
:guide-author: Open Liberty
= Configuring microservices for different environments with MicroProfile Config Profile

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Explore how to externalize configuration using MicroProfile Config and configure microservices for different environments with MicroProfile Config Profile.

// ===========================================================================================
== What you'll learn
You will learn how to configure multiple environments by providing specific set of configuration properties for each environment with Config Profile. You will also explore the features to externalize your microservice's configuration properties.

and more...


// ===========================================================================================
// Getting Started

[role=command]
include::{common-includes}/gitclone.adoc[]


// ===========================================================================================
== Trying the application

TBA...

Navigate to the `start/system` directory.

[role='command']
----
mvn -P testing liberty:run
----

...

Navigate to the `start/query` directory.

[role='command']
----
mvn liberty:dev
----

run the url http://localhost:9085/query/systems/localhost

Stop the `system` service and restart it with development configuration
[role='command']
----
mvn -P development liberty:run
----

...

// ===========================================================================================
== Adding configuration profile

TBA...

run the url http://localhost:9085/query/systems/localhost and get error

=== Creating configuration profile in properties level

TBA...

// Replace microprofile-config.properties
[role="code_command hotspot file=0", subs="quotes"]
----
#Replace the `microprofile-config.properties` file.#
`src/main/resources/META-INF/microprofile-config.properties`
----

microprofile-config.properties
[source, properties, linenums, role="code_column"]
----
include::staging/query/src/main/resources/META-INF/microprofile-config.properties[]
----

add [hotspot=development file=0]`%development` properties

Stop the `query` service by...


Restart 

[role='command']
----
mvn liberty:dev -Dliberty.var.mp.config.profile="development"
----


run the url http://localhost:9085/query/systems/localhost and success

=== Creating configuration profile using ConfigSource

TBA...

// Create microprofile-config-development.properties
[role="code_command hotspot file=0", subs="quotes"]
----
#Create the `microprofile-config-development.properties` file.#
`src/main/resources/META-INF/microprofile-config-development.properties`
----

microprofile-config-development.properties
[source, properties, linenums, role="code_column hide_tags=userPassword,properties,contactEmail"]
----
include::finish/query/src/main/resources/META-INF/microprofile-config-development.properties[]
----

Define the [hotspot=system file=0]`system.*` properties for development configuration

// Replace microprofile-config.properties
[role="code_command hotspot file=0", subs="quotes"]
----
#Replace the `microprofile-config.properties` file.#
`src/main/resources/META-INF/microprofile-config.properties`
----

microprofile-config.properties
[source, properties, linenums, role="code_column hide_tags=development"]
----
include::staging/query/src/main/resources/META-INF/microprofile-config.properties[]
----

Remove the `%development.*` properties.

Stop the `query` service by...


Restart 

[role='command']
----
mvn liberty:dev -Dliberty.var.mp.config.profile="development"
----

run the url http://localhost:9085/query/systems/localhost and success


// ===========================================================================================
== Defining property with expressions

TBA...

// File 0
// Replace microprofile-config-development.properties
[role="code_command hotspot file=0", subs="quotes"]
----
#Replace the `microprofile-config-development.properties` file.#
`src/main/resources/META-INF/microprofile-config-development.properties`
----

microprofile-config-development.properties
[source, properties, linenums, role="code_column hide_tags=properties,contactEmail"]
----
include::finish/query/src/main/resources/META-INF/microprofile-config-development.properties[]
----

add the [hotspot=userPassword file=0]`system.userPassword` property that is constructed by `system.user` and `system.password`


// File 1
// Replace SystemResource.java
[role="code_command hotspot file=1", subs="quotes"]
----
#Replace the `SystemResource` class.#
`src/main/java/io/openliberty/guides/query/SystemResource.java`
----

SystemResource.java
[source, java, linenums, role="code_column hide_tags=copyright"]
----
include::staging/query/src/main/java/io/openliberty/guides/query/SystemResource.java[]
----

Replace the `system.user` and `system.password` configuration properties by the [hotspot=userPassword file=1]`system.userPassword` property.

Use the [hotspot=authHeader file=1]`systemUserPassword` configuration property to construct the authorization header.

run the url http://localhost:9085/query/systems/localhost and success

// ===========================================================================================
== Retrieving property as a list

TBA...

// File 0
// Replace microprofile-config-development.properties
[role="code_command hotspot file=0", subs="quotes"]
----
#Replace the `microprofile-config-development.properties` file.#
`src/main/resources/META-INF/microprofile-config-development.properties`
----

microprofile-config-development.properties
[source, properties, linenums, role="code_column hide_tags=roleAndQuery"]
----
include::finish/query/src/main/resources/META-INF/microprofile-config-development.properties[]
----

add the [hotspot=properties file=0]`system.properties` property that contains a list of property names seperated by comma.

// File 1
// Replace SystemResource.java
[role="code_command hotspot file=1", subs="quotes"]
----
#Replace the `SystemResource` class.#
`src/main/java/io/openliberty/guides/query/SystemResource.java`
----

SystemResource.java
[source, java, linenums, role="code_column hide_tags=copyright"]
----
include::finish/query/src/main/java/io/openliberty/guides/query/SystemResource.java[]
----

Add the [hotspot=systemPropertiesProperty file=1]`system.properties` configuration property that is defined with `List<String>` type.

Iterate through the [hotspot=systemProperties file=1]`systemProperties` list to retreve all property values by calling the `systemClient` REST client.

run the url http://localhost:9085/query/systems/localhost and see more properties.

// ===========================================================================================
== Using configuration source APIs

TBA...

// File 0
// Replace microprofile-config-development.properties
[role="code_command hotspot file=0", subs="quotes"]
----
#Replace the `microprofile-config-development.properties` file.#
`src/main/resources/META-INF/microprofile-config-development.properties`
----

microprofile-config-development.properties
[source, properties, linenums, role="code_column"]
----
include::finish/query/src/main/resources/META-INF/microprofile-config-development.properties[]
----

add the [hotspot=roleAndQuery file=0]`role` and [hotspot=roleAndQuery file=0]`query.*` properties.

The [hotspot=contactEmail file=0]`query.contactEmail` property specifies `admin` as the default value, and uses composed expression where the `${role}` inner expressions is resolved first.

// File 1
// Create ConfigResource.java
[role="code_command hotspot file=1", subs="quotes"]
----
#Create the `ConfigResource` class.#
`src/main/java/io/openliberty/guides/query/ConfigResource.java`
----

ConfigResource.java
[source, java, linenums, role="code_column hide_tags=copyright,systemConfig,getSystemConfig"]
----
include::finish/query/src/main/java/io/openliberty/guides/query/ConfigResource.java[]
----

Explain different APIs, e.g [hotspot=config file=1]`Config` class provides..., [hotspot=configValue file=1]`ConfigValue` claass provides..., ...

run the urls http://localhost:9085/query/config and http://localhost:9085/query/config/contact

// ===========================================================================================
== Aggregating configuration properties into a CDI bean

TBA...

// File 0
// Create ConfigSystemBean.java
[role="code_command hotspot file=0", subs="quotes"]
----
#Create the `ConfigSystemBean` class.#
`src/main/java/io/openliberty/guides/query/ConfigSystemBean.java`
----

ConfigSystemBean.java
[source, properties, linenums, role="code_column hide_tags=copyright"]
----
include::finish/query/src/main/java/io/openliberty/guides/query/ConfigSystemBean.java[]
----

Annotate the `ConfigSystemBean` class by [hotspot=prefix file=0]`@ConfigProperties` annotation with setting the `prefix` attribute to `system`... 

and more...

// File 1
// Replace ConfigResource.java
[role="code_command hotspot file=1", subs="quotes"]
----
#Replace the `ConfigResource` class.#
`src/main/java/io/openliberty/guides/query/ConfigResource.java`
----

ConfigResource.java
[source, java, linenums, role="code_column hide_tags=copyright"]
----
include::finish/query/src/main/java/io/openliberty/guides/query/ConfigResource.java[]
----

Inject the [hotspot=systemConfig file=1]`systemConfig` field variable ... ,

Add the [hotspot=getSystemConfig file=1]`/query/config/system` endpoint ...

run url http://localhost:9085/query/config/system


// ===========================================================================================
== Testing the application

TBA...

== Great work! You're done!

You just learnt how to use Microfile Config Profile to configure the application for multiple environments.

Feel free to try one of the related guides. They demonstrate new technologies that you can learn and expand on top what you built in this guide.

include::{common-includes}/attribution.adoc[subs="attributes"]