// Copyright (c) 2022 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//   IBM Corporation
:projectid: microprofile-config-profile
:page-layout: guide-multipane
:page-duration: 20 minutes
:page-releasedate: 2022-12-31
:page-description: Learn how to use MicroProfile Config Profiles to provide configurations for different environments and development stages.
:page-tags: ['MicroProfile']
:page-permalink: /guides/{projectid}
:page-related-guides: ['microprofile-config-intro']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/prod
:source-highlighter: prettify
:page-seo-title: Configuring Java microservices with different environments and development stages using MicroProfile Config Profiles
:page-seo-description: A tutorial and example on how to externalize configuration properties and configure multiple project environments and development stages for Java microservices using MicroProfile Config Profile.
:guide-author: Open Liberty
= Configuring microservices for different environments

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Learn how to use MicroProfile Config Profiles to provide configurations for different environments and development stages.

:win: WINDOWS
:mac: MAC
:linux: LINUX

// =================================================================================================
// What you'll learn
// =================================================================================================
== What you'll learn

You'll learn how to configure multiple environments into a microservice by providing different sets of configuration properties for each environment. From development to production and across your DevOps environments, https://download.eclipse.org/microprofile/microprofile-config-3.0/microprofile-config-spec-3.0.html#configprofile[MicroProfile Config Profile^] gives you flexibility to set and choose configuration for your microservices depending on the current project stage efficiently. This guide assumes you are familiar with https://download.eclipse.org/microprofile/microprofile-config-3.0/microprofile-config-spec-3.0.html#_microprofile_config[MicroProfile Config^]. If you're new to MicroProfile Config, you might want to start with the https://openliberty.io/guides/microprofile-config-intro.html[Separating configuration from code in microservices^] guide and the https://openliberty.io/guides/microprofile-config.html[Configuring microservices^] guide first.

The application that you will be working with is a `query` service. It fetches properties from the `system` microservices. The `system` microservice will use different port and require different user when running in the testing and development environments. You'll provide the `query` service with different configurations using MicroProfile Config Profiles, so that it can access different environments of the `system` service.

// =================================================================================================
// Getting Started
// =================================================================================================

[role=command]
include::{common-includes}/gitclone.adoc[]

// =================================================================================================
== Trying the application

The starting Java project, which you can find in the `start` directory, is a multi-module Maven project that's made up of the `system` and `query` microservices. Each microservice resides in its own corresponding directory, `system` and `query`. 

The `system` microservice contains the two build profiles: `testing` and `development`. To start the `system` service in `testing` environment, navigate to the `start/system` directory and run the following Maven goal to build the service and deploy it to Open Liberty:

[role='command']
```
cd start/system
mvn -P testing liberty:run
```

// file 0
system/server.xml
[source, XML, linenums, role='code_column']
----
include::finish/system/src/main/liberty/config/server.xml[]
----

In the `testing` environment, the default configuration from the [hotspot=defaultConfig file=0]`server.xml` file is used. You can find out that the `system` service is running on port [hotspot=port hotspot=httpEndpoint file=0]`9080` with context root [hotspot=context.root hotspot=webApplication file=0]`system`. In addition, a basic user registry is configured with the username [hotspot=username hotspot=user file=0]`bob` and the password [hotspot=password hotspot=user file=0]`bobpwd` as the authorized access to the resources from other services.

Next, open another command-line session and navigate to the `start/query` directory. 

[role='command']
```
cd start/query
```

When you run Open Liberty in development mode, known as dev mode, the server listens for file changes and automatically recompiles and deploys your updates whenever you save a new change. Run the following commands to start the `query` service in dev mode:

[role='command']
```
mvn liberty:dev
```

After you see the following message, your application server in dev mode is ready:

[source, role="no_copy"]
----
**************************************************
*     Liberty is running in dev mode.
----

Dev mode holds your command-line session to listen for file changes. Open another command-line session to continue, or open the project in your editor.

// file 1
query/microprofile-config.properties
[source, Properties, linenums, role='code_column']
----
include::start/query/src/main/resources/META-INF/microprofile-config.properties[]
----

Navigate to the `start` directory and check out the [hotspot=system file=1]`query/src/main/resources/META-INF/microprofile-config.properties` MicroProfile configuration file. This configuration file is the default ConfigSource that defines the required properties to access the `testing` environment of the `system` service.

Point your browser to the http://localhost:9085/query/systems/localhost URL. You are expected to see the current OS and Java version in JSON format. The URL retrieves the system property information for the `localhost` host name by making a request to the `system` service at `\http://localhost:9080/system/property/{property}`.

After you are finished checking out the application, stop the `system` service by pressing `CTRL+C` in the command-line session where you ran the server. Alternatively, you can run the `liberty:stop` goal from the `start/system` directory in another shell session:

[role='command']
```
mvn liberty:stop

```

// =================================================================================================
== Switching to development environment

// file 0
system/pom.xml
[source, XML, linenums, role='code_column']
----
include::finish/system/pom.xml[]
----

Restart the `system` service in [hotspot=development file=0]`development` environment by running the following Maven goal from the `start/system` directory:

[role='command']
```
mvn liberty:dev
```

After you see the following message, your application server in dev mode is ready:

[source, role="no_copy"]
----
**************************************************
*     Liberty is running in dev mode.
----

Now, the Maven properties from the [hotspot=development file=0]`development` profile override the default configuration values from the `system/server.xml` file. You can find out from the [hotspot file=0]`system/pom.xml` file that the `system` service is now running on port [hotspot=port file=0]`9081` with context root [hotspot=context.root file=0]`system/dev`. In addition, the credentials for the user registry are updated with the new username [hotspot=username file=0]`alice` and the new password [hotspot=password file=0]`alicepwd`.

Try to access the http://localhost:9085/query/systems/localhost URL. The `query` service returns the message: `{"fail":"Failed to reach the client localhost."}`.

// file 1
query/microprofile-config.properties
[source, Properties, linenums, role='code_column']
----
include::start/query/src/main/resources/META-INF/microprofile-config.properties[]
----

It is caused by the `system` service is started with the `development` profile, but the current configuration properties defined in the [hotspot=system file=1]`META-INF/microprofile-config.properties` file at the `query` service are the values for accessing the `system` service at the `testing` environment.


// =================================================================================================
== Creating configuration profile in properties level

MicroProfile Config Profiles allow configurations for different environments such as development, testing, and production while only a single profile is active. The active profile is specified by using the `mp.config.profile` property, which can be set in any of the https://download.eclipse.org/microprofile/microprofile-config-3.0/microprofile-config-spec-3.0.html#configsource[ConfigSources^] or at application startup. Once it is set, the corresponding set of configuration properties that are associated with the active profile are used. 

Now, navigate to the `start` directory to create configuration profile for the `query` service in different ways.

You can provide configuration properties for the `development` environment at the properties level by setting its name in the following format: `%<mp.config.profile>.<original property name>`. 

[role="code_command hotspot file=0", subs="quotes"]
----
#Replace the `microprofile-config.properties` file.#
`query/src/main/resources/META-INF/microprofile-config.properties`
----

// file 0
query/microprofile-config.properties
[source, properties, linenums, role="code_column"]
----
include::staging/query/src/main/resources/META-INF/microprofile-config.properties[]
----

// file 1
system/pom.xml
[source, XML, linenums, role='code_column']
----
include::finish/system/pom.xml[]
----

Configure the [hotspot=development file=0]`%development.*` properties in the `microprofile-config.properties` file according to the values from the [hotspot=developmentProperties file=1]`development` profile of the `system` service.

Next, stop the `query` service by pressing `CTRL+C` in the command-line session where you ran the `query` service, or by typing `q` and then pressing the `enter/return` key.

Restart the `query` service with the `development` MicroProfile Config Profile by running the following Maven goal from the `start/query` directory:

[role='command']
```
mvn liberty:dev -Dliberty.var.mp.config.profile="development"
```

With setting `mp.config.profile` to `development`, each `%development.*` property overrides the value of its original property. For example, the [hotspot=dev.port file=0]`%development.system.httpPort` property overrides the [hotspot=port file=0]`system.httpPort` property and the value is resolved to `9081`.

Now, you can access the application by the http://localhost:9085/query/systems/localhost URL. You are expected to see the current OS and Java version in JSON format.

// =================================================================================================
== Creating configuration profile using ConfigSource

You can also provide multiple ConfigSources with the names formatted as `microprofile-config-<mp.config.profile>.properties` under the `META-INF` directory.


// file 0
[role="code_command hotspot file=0", subs="quotes"]
----
#Create the `microprofile-config-development.properties` file.#
`query/src/main/resources/META-INF/microprofile-config-development.properties`
----

query/microprofile-config-development.properties
[source, properties, linenums, role="code_column hide_tags=userPassword,properties,contactEmail,roleAndQuery"]
----
include::finish/query/src/main/resources/META-INF/microprofile-config-development.properties[]
----

// file 1
system/pom.xml
[source, XML, linenums, role='code_column']
----
include::finish/system/pom.xml[]
----

Define the [hotspot=system file=0]`system.*` properties in the `microprofile-config-development.properties` file according to the values from the [hotspot=developmentProperties file=1]`development` profile of the `system` service.


// file 2
[role="code_command hotspot file=2", subs="quotes"]
----
#Replace the `microprofile-config.properties` file.#
`query/src/main/resources/META-INF/microprofile-config.properties`
----

query/microprofile-config.properties
[source, properties, linenums, role="code_column hide_tags=development"]
----
include::staging/query/src/main/resources/META-INF/microprofile-config.properties[]
----

Remove all the `%development.*` properties from the `microprofile-config.properties` file.

Because the active profile is `development`, the [hotspot file=0]`microprofile-config-development.properties` file is loaded on top of the default `microprofile-config.properties` file. The [hotspot=system file=0]`system.*` properties from `microprofile-config-development.properties` file thus take precedence.

Because you are running the `query` service in dev mode, the changes that you made were automatically picked up. Go to the http://localhost:9085/query/systems/localhost URL to check out the application again. You see the current OS and Java version in JSON format.


// ===========================================================================================
== Implementing test cases

You will create endpoint tests to test the basic functionality of the `query` microservice. If a test failure occurs, then you might have introduced a bug into the code.

// file 0
[role="code_command hotspot file=0", subs="quotes"]
----
#Create the `QueryEndpointIT` class.#
`query/src/test/java/it/io/openliberty/guides/query/QueryEndpointIT.java`
----

QueryEndpointIT.java
[source, java, linenums, role="code_column hide_tags=copyright"]
----
include::finish/query/src/test/java/it/io/openliberty/guides/query/QueryEndpointIT.java[]
----

// file 1
query/pom.xml
[source, XML, linenums, role='code_column']
----
include::finish/query/pom.xml[]
----

See the following descriptions of the test cases:

* [hotspot=testQuerySystem file=0]`testQuerySystem()` verifies the `/query/systems/{hostname}` endpoint.

* [hotspot=testUnknownHost file=0]`testUnknownHost()` verifies that an unknown host or a host that does not expose their JVM system properties is correctly handled with a fail message.

**Running the tests**

Because you started Open Liberty in dev mode, you can run the tests by pressing the enter/return key from the command-line session where you started the `query` service. If the tests pass, you see a similar output to the following example:

[source, role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.query.QueryEndpointIT
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.703 s - in it.io.openliberty.guides.query.QueryEndpointIT

Results:

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
----

When you are done checking out the application in `development` environment, exit dev mode by pressing `CTRL+C` in the command-line sessions where you ran the `system` and `query` services, or by typing `q` and then pressing the `enter/return` key. Alternatively, you can run the `liberty:stop` goal from the `start` directory in another command-line session for the `system` and `query` services:
// static guide instruction
ifndef::cloud-hosted[]
[role="command"]
----
mvn -pl system liberty:stop
mvn -pl query liberty:stop
----
endif::[]
// cloud hosted instruction
ifdef::cloud-hosted[]
```bash
cd /home/project/guide-microprofile-config-profile/start
mvn -pl system liberty:stop
mvn -pl backendServices liberty:stop
```
endif::[]

// ===========================================================================================
== Testing the application

Before testing the application in the `testing` environment, update the `microprofile-config.properties` file with the new `system.userPassword`, `system.properties`, `role`, and `query.*` properties that were added in the previous section.

// file 0
[role="code_command hotspot file=0", subs="quotes"]
----
#Replace the `microprofile-config.properties` file.#
`query/src/main/resources/META-INF/microprofile-config.properties`
----

query/microprofile-config.properties
[source, properties, linenums, role="code_column hide_tags=copyright"]
----
include::finish/query/src/main/resources/META-INF/microprofile-config.properties[]
----


Navigate to the `start` directory to test the application by running the following script:

include::{common-includes}/os-tabs.adoc[]

[.tab_content.mac_section.linux_section]
--
[role='command']
```
./scripts/testApp.sh
```
--

[.tab_content.windows_section]
--
[role='command']
```
scripts\testApp.bat
```
--


If the tests pass, you see a similar output to the following example:

[source, role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.system.SystemEndpointIT
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.539 s - in it.io.openliberty.guides.system.SystemEndpointIT

Results:

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

...

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.query.QueryEndpointIT
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.706 s - in it.io.openliberty.guides.query.QueryEndpointIT

Results:

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0

----


== Great work! You're done!

You just learnt how to use Microfile Config Profile to configure the application for multiple environments.

Feel free to try one of the related guides. They demonstrate new technologies that you can learn and expand on top what you built in this guide.

include::{common-includes}/attribution.adoc[subs="attributes"]