// Copyright (c) 2022 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//   IBM Corporation
:projectid: microprofile-config-profile
:page-layout: guide-multipane
:page-duration: 30 minutes
:page-releasedate: 2022-12-09
:page-description: Learn how to use MicroProfile Config specification to provide configurations for different Config Profiles depending on project environment.
:page-tags: ['MicroProfile']
:page-permalink: /guides/{projectid}
:page-related-guides: ['microprofile-config-intro']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/prod
:source-highlighter: prettify
:page-seo-title: Configuring microservices for different environments with MicroProfile Config Profile
:page-seo-description: A tutorial and example on how to externalize configuration properties and configure multiple project environments for Java microservices using Eclipse MicroProfile Config.
:guide-author: Open Liberty
= Configuring microservices for different environments with MicroProfile Config Profile

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Learn how to use MicroProfile Config specification to provide configurations for different Config Profiles depending on project environment.

// =================================================================================================
// What you'll learn
// =================================================================================================
== What you'll learn

Explore how to configure multiple environments into a microservice by providing specific set of configuration properties for each environment. From development to production and across your DevOps environments, Config Profile gives you flexibility to set and choose configuration for your microservices depending on the current project stage efficiently. This guide assumes you are familiar with MicroProfile Config. If you're new to MicroProfile Config, you might want to start with the https://openliberty.io/guides/microprofile-config-intro.html[Separating configuration from code in microservices^] guide and the https://openliberty.io/guides/microprofile-config.html[Configuring microservices^] guide first.

Furthermore, you'll learn to define properties with expressions, retrieve multi-valued config property values as a list, retrieve details about the underlying configuration of your microservice, and aggregate related properties into a single property class.

The application that you will be working with is a `query` service, which fetches the system property information for the running host. Whenever a request is made to retrieve the system properties of the running host, the `query` service will create a client to invoke the `system` service on that host. The `system` service simulates a remote service in the application.

// =================================================================================================
// Getting Started
// =================================================================================================

[role=command]
include::{common-includes}/gitclone.adoc[]

// =================================================================================================
// Trying the application
// =================================================================================================
== Trying the application

// file 0
system/server.xml
[source, XML, linenums, role='code_column']
----
include::start/system/src/main/liberty/config/server.xml[]
----

// file 1
microprofile-config.properties
[source, Properties, linenums, role='code_column']
----
include::start/query/src/main/resources/META-INF/microprofile-config.properties[]
----

// file 2
system/pom.xml
[source, XML, linenums, role='code_column']
----
include::start/system/pom.xml[]
----

The starting Java project, which you can find in the `start` directory, is a multi-module Maven project that's made up of the `system` and `query` microservices. Each microservice resides in its own directory, `start/system` and `start/query`. 

The `system` microservice contains the two build profiles: `testing` and `development`. To start the `system` service in `testing` environment, navigate to the `start/system` directory and run the following Maven goal to build the service and deploy it to Open Liberty:

[role='command']
```
cd start/system
mvn -P testing liberty:run
```

In the `testing` environment, the default application configuration from the `src/main/liberty/config/server.xml` file is used. You can find out from the [hotspot file=0]`system/server.xml` file that the `system` service is running on port [hotspot=port file=0]`9080` with context root [hotspot=context.root file=0]`system`. In addition, a basic user registry is configured with the username [hotspot=username file=0]`bob` and the password [hotspot=password file=0]`bobpwd` as the authorized access to the resources from other services.

Next, open another command-line session and navigate to the `start/query` directory. 

[role='command']
```
cd start/query
```

When you run Open Liberty in development mode, known as dev mode, the server listens for file changes and automatically recompiles and deploys your updates whenever you save a new change. Run the following commands to start the `query` service in dev mode:

[role='command']
```
mvn liberty:dev
```

After you see the following message, your application server in dev mode is ready:

[source, role="no_copy"]
----
**************************************************
*     Liberty is running in dev mode.
----

Dev mode holds your command-line session to listen for file changes. Open another command-line session to continue, or open the project in your editor.

Access the [hotspot file=1]`src/main/resources/META-INF/microprofile-config.properties` local configuration file to check some static configuration. This configuration file is the default ConfigSource for an application that uses MicroProfile Config. Each property that has been defined in this file corresponds to a property that is required to access the `testing` environment of the`system` service.

Point your browser to the http://localhost:9085/query/systems/localhost URL. The URL retrieves the system property information for the `localhost` hostname by making a request to the `system` service.

After you are finished checking out the application, stop the `system` service by pressing `CTRL+C` in the command-line session where you ran the server. Alternatively, you can run the `liberty:stop` goal from the `start/system` directory in another shell session:

[role='command']
```
mvn liberty:stop
```

Then, restart the `system` service in `development` environment by running the following Maven goal from the `start/system` directory:

[role='command']
```
mvn -P development liberty:run
```

Now, the configuration properties from the [hotspot=development file=2]`development` profile override the default configuration values from the `system/server.xml` file. You can find out from the [hotspot file=2]`system/pom.xml` file that the `system` service is now running on port [hotspot=port file=2]`9081` with context root [hotspot=context.root file=2]`system/dev`. In addition, the credentials for the user registry are updated with the new username [hotspot=username file=2]`alice` and the new password [hotspot=password file=2]`alicepwd`.

// =================================================================================================
// Adding configuration profile
// =================================================================================================
== Adding configuration profile

// file 0
microprofile-config.properties
[source, Properties, linenums, role='code_column']
----
include::start/query/src/main/resources/META-INF/microprofile-config.properties[]
----

Config Profiles allow configuration for different environments such as development, testing, and production while only a single profile is active. The active Config Profile is specified by using the `mp.config.profile` property, which can be set in any of the ConfigSources or at application startup. Once it is set, the corresponding set of configuration properties that are associated with the active profile are used. 

Try to access the http://localhost:9085/query/systems/localhost URL. The `query` service returns the message, `{"fail":"Failed to reach the client localhost."}`, because the current configuration properties defined in the [hotspot file=0]`microprofile-config.properties` file map to the required values to access the `testing` environment of the `system` service while the service is started with the `development` profile.

=== Creating configuration profile in properties level

A configuration property can be used at the property level by setting its name in the format: `%<mp.config.profile>.<original property name>`. 

[role="code_command hotspot file=0", subs="quotes"]
----
#Replace the `microprofile-config.properties` file.#
`src/main/resources/META-INF/microprofile-config.properties`
----

// file 0
microprofile-config.properties
[source, properties, linenums, role="code_column"]
----
include::staging/query/src/main/resources/META-INF/microprofile-config.properties[]
----

Configure the [hotspot=development file=0]`%development.*` properties with the value of the system property variables from the `development` profile of the `system` service.

Next, stop the `query` service by pressing `CTRL+C` in the command-line session where you ran the `query` service, or by typing `q` and then pressing the `enter/return` key.

Then, restart the `query` service with the `development` configuration profile by running the following Maven goal from the `start/query` directory:

[role='command']
```
mvn liberty:dev -Dliberty.var.mp.config.profile="development"
```

With `mp.config.profile` set to `development`, each `%development.*` property overrides the value of its original property. For example, the property [hotspot=dev.port file=0]`%development.system.httpPort` overrides the property [hotspot=port file=0]`system.httpPort` and the value is resolved to `9081`.

Now, you can access the application by the http://localhost:9085/query/systems/localhost URL. You are expected to see the current OS and Java version displayed in JSON format.

=== Creating configuration profile using ConfigSource

Configuration properties can also be used at the ConfigSource level. Multiple config sources can be provided with the name formatted as `microprofile-config-<mp.config.profile>.properties` under the `META-INF` folder on the classpath so they can be used for specific selected profiles.

// file 0
[role="code_command hotspot file=0", subs="quotes"]
----
#Create the `microprofile-config-development.properties` file.#
`src/main/resources/META-INF/microprofile-config-development.properties`
----

microprofile-config-development.properties
[source, properties, linenums, role="code_column hide_tags=userPassword,properties,contactEmail,roleAndQuery"]
----
include::finish/query/src/main/resources/META-INF/microprofile-config-development.properties[]
----

Define the [hotspot=system file=0]`system.*` properties with the system property variables from the `development` configuration of the `system` service.

To use the configuration properties in [hotspot file=0]`microprofile-config-development.properties`,

// file 1
[role="code_command hotspot file=1", subs="quotes"]
----
#Replace the `microprofile-config.properties` file.#
`src/main/resources/META-INF/microprofile-config.properties`
----

microprofile-config.properties
[source, properties, linenums, role="code_column hide_tags=development"]
----
include::staging/query/src/main/resources/META-INF/microprofile-config.properties[]
----

Remove all the `%development.*` properties from the [hotspot file=1]`microprofile-config.properties` file.

Because the `mp.config.profile` is set to `development`, the file [hotspot file=0]`microprofile-config-development.properties` is loaded on top of the default [hotspot file=1]`microprofile-config.properties` file. The [hotspot=system file=0]`system.*` properties from [hotspot file=0]`microprofile-config-development.properties` thus take precedence.

Because you are running the `query` service in dev mode, the changes that you made were automatically picked up. Go to the http://localhost:9085/query/systems/localhost URL to test out the application again. The current OS and Java version are displayed.

// =================================================================================================
// Defining property with expressions
// =================================================================================================
== Defining property with expressions

The value of a config property may contain an expression corresponding to another config property. Property expressions provide a way to embed expression segments in property values using the `${}` sequence.

Additionally, you can also implement expressions with the following syntax:

* `${prop:default}` - Provides a `default` value after the `:` if the expression doesn't find a value for the property `prop`.

* `${prop${compose}}` - Composed expressions where inner expressions are resolved first.

* `${prop1}${prop2}` - Multiple expressions.

// file 0
[role="code_command hotspot file=0", subs="quotes"]
----
#Replace the `microprofile-config-development.properties` file.#
`src/main/resources/META-INF/microprofile-config-development.properties`
----

microprofile-config-development.properties
[source, properties, linenums, role="code_column hide_tags=properties,contactEmail"]
----
include::finish/query/src/main/resources/META-INF/microprofile-config-development.properties[]
----

Add the [hotspot=userPassword file=0]`system.userPassword` configuration property that is constructed by property [hotspot=user file=0]`system.user` and property [hotspot=password file=0]`system.password` to the `microprofile-config-development.properties` file.

The property [hotspot=userPassword file=0]`system.userPassword` is expanded to `alice:alicepwd`.

To use this configuration property,

// file 1
[role="code_command hotspot file=1", subs="quotes"]
----
#Replace the `SystemResource` class.#
`src/main/java/io/openliberty/guides/query/SystemResource.java`
----

SystemResource.java
[source, java, linenums, role="code_column hide_tags=copyright"]
----
include::staging/query/src/main/java/io/openliberty/guides/query/SystemResource.java[]
----

Replace the injection of the `system.user` and `system.password` configuration properties with the [hotspot=userPassword file=1]`system.userPassword` property, and use the value of [hotspot=authHeader file=1]`systemUserPassword` to construct the authorization header.

Because you are running the `query` service in dev mode, the changes that you made were automatically picked up. Check out the service that you created at the http://localhost:9085/query/systems/localhost URL. The current OS and Java version are displayed.

// ===========================================================================================
== Retrieving property as a list

Configuration values are purely Strings. MicroProfile Config API has built-in converters that automatically converts configured Strings into target types as well as supports the retrieval of multi-valued properties as lists.

// file 0
[role="code_command hotspot file=0", subs="quotes"]
----
#Replace the `microprofile-config-development.properties` file.#
`src/main/resources/META-INF/microprofile-config-development.properties`
----

microprofile-config-development.properties
[source, properties, linenums, role="code_column hide_tags=roleAndQuery"]
----
include::finish/query/src/main/resources/META-INF/microprofile-config-development.properties[]
----

Add the [hotspot=properties file=0]`system.properties` property that contains a list of property names seperated by comma to the [hotspot file=0]`microprofile-config-development.properties` file.

To use this configuration property,

// file 1
[role="code_command hotspot file=1", subs="quotes"]
----
#Replace the `SystemResource` class.#
`src/main/java/io/openliberty/guides/query/SystemResource.java`
----

SystemResource.java
[source, java, linenums, role="code_column hide_tags=copyright"]
----
include::finish/query/src/main/java/io/openliberty/guides/query/SystemResource.java[]
----

Inject the [hotspot=systemPropertiesProperty file=1]`system.properties` configuration property as a `List<String>` type.

Then, modify the [hotspot=getSystemPropertiesMethod file=1]`getSystemProperties` method. Iterate through the [hotspot=systemProperties file=1]`systemProperties` list to retreve all specified property values by the `systemClient` REST client.

Because you are running the `query` service in dev mode, the changes that you made were automatically picked up. Alternatively, you can type `r` and press Enter in the command-line session where you ran the `query` service to restart the server .

Point your browser to the http://localhost:9085/query/systems/localhost URL. You see a result in JSON format with the system properties specified in the [hotspot=systemPropertiesProperty file=1]`system.properties` configuration property of your local JVM.

// ===========================================================================================
== Using configuration source APIs

MicroProfile Config provides configuration source APIs for retrieving details about configuration properties. The ConfigValue API class holds a variety of useful information about a single specified config property. The Config API class on the other hand exposes the lookup metadata of all configuration properties. 

You'll implement endpoints that retrieve configuration information that is specific to this guide by using the two API classes.

// file 0
[role="code_command hotspot file=0", subs="quotes"]
----
#Replace the `microprofile-config-development.properties` file.#
`src/main/resources/META-INF/microprofile-config-development.properties`
----

microprofile-config-development.properties
[source, properties, linenums, role="code_column"]
----
include::finish/query/src/main/resources/META-INF/microprofile-config-development.properties[]
----

Add the [hotspot=role file=0]`role` and [hotspot=query file=0]`query.*` properties to the [hotspot file=0]`microprofile-config-development.properties` file.

The [hotspot=contactEmail file=0]`query.contactEmail` property specifies `admin` as the default value, and uses composed property expression where the `${role}` inner expressions is resolved first.

// file 1
[role="code_command hotspot file=1", subs="quotes"]
----
#Create the `ConfigResource` class.#
`src/main/java/io/openliberty/guides/query/ConfigResource.java`
----

ConfigResource.java
[source, java, linenums, role="code_column hide_tags=copyright,systemConfig,getSystemConfig"]
----
include::finish/query/src/main/java/io/openliberty/guides/query/ConfigResource.java[]
----

Inject the [hotspot=configValue file=1]`query.contactEmail` property as usual, only this time define the type as `ConfigValue`. This ConfigValue metadata object holds additional information after the lookup of the [hotspot=configValue file=1]`query.contactEmail` configuration property. The [hotspot=getSourceName file=1]`getSourceName()` method determines which ConfigSource has the highest ordinal for the specified property. The [hotspot=getSourceOrdinal file=1]`getSourceOrdinal()` method returns the ordinal value of the ConfigSource that loaded the property lookup. The [hotspot=getValue file=1]`getValue()` methods returns the value of the config property.

You can also retrieve the information of all config properties of the underlying configuration. 

Inject the [hotspot=config file=1]`Config` metadata object. The [hotspot=getConfigSources file=1]`getConfigSources()` method returns all of the currently registered configuration sources for the running service. The [hotspot=getPropertyNames file=1]`getPropertyNames()` method finds all configuration property names by searching through all configured ConfigSources.

Because you are running the `query` service in dev mode, the changes that you made were automatically picked up. Alternatively, you can type `r` and press Enter in the command-line session where you ran the `query` service to restart the server .

Point your browser to the http://localhost:9085/query/systems/localhost URL. You see a result in JSON format with the system properties specified in the [hotspot=systemPropertiesProperty file=1]`system.properties` configuration property of your local JVM.

Point your browser to the http://localhost:9085/query/config/contact URL. You see the source name, source ordinal, and value of propterty `query.contactEmail`. 

Next, point your browser to the http://localhost:9085/query/config URL. You see all registered configuration sources and property names of the running `query` service.

// ===========================================================================================
== Aggregating configuration properties into a CDI bean

With Microprofile Config, you can aggregate configuration properties starting with the same prefix into a single property class through the `@ConfigProperties` annotation.

// file 0
[role="code_command hotspot file=0", subs="quotes"]
----
#Create the `ConfigSystemBean` class.#
`src/main/java/io/openliberty/guides/query/ConfigSystemBean.java`
----

ConfigSystemBean.java
[source, java, linenums, role="code_column hide_tags=copyright"]
----
include::finish/query/src/main/java/io/openliberty/guides/query/ConfigSystemBean.java[]
----

Define a CDI bean for the configuration properties that share the common prefix `system.`.

Annotate the [hotspot=ConfigSystemBean file=0]`ConfigSystemBean` class with [hotspot=prefix file=0]`@ConfigProperties` annotation. The `@ConfigProperties` 's `prefix` attribute specifies the common prefix of the configuration properties.

To use this [hotspot=ConfigSystemBean file=0]`ConfigSystemBean` class,

// file 1
[role="code_command hotspot file=1", subs="quotes"]
----
#Replace the `ConfigResource` class.#
`src/main/java/io/openliberty/guides/query/ConfigResource.java`
----

ConfigResource.java
[source, java, linenums, role="code_column hide_tags=copyright"]
----
include::finish/query/src/main/java/io/openliberty/guides/query/ConfigResource.java[]
----

Inject the `ConfigSystemBean` CDI bean to the [hotspot=systemConfig file=1]`systemConfig` field variable by using the [hotspot=inject file=1]`@Inject` and the [hotspot=ConfigProperties file=1]`@ConfigProperties` annotations.

Implement the [hotspot=getSystemConfig file=1]`/query/config/system` endpoint. This endpoint uses the `ConfigSystemBean` bean class to retrieve the config property values of the `system.*` properties without having to inject them one by one.

Because you are running the `query` service in dev mode, the changes that you made were automatically picked up. Go to the http://localhost:9085/query/config/system URL. You see all configuration properties prefixed with `system` and their values.

// ===========================================================================================
== Testing the application

You will create endpoint tests to test the basic functionality of the `query` microservice. If a test failure occurs, then you might have introduced a bug into the code.

// file 0
[role="code_command hotspot file=0", subs="quotes"]
----
#Create the `QueryEndpointIT` class.#
`src/test/java/it/io/openliberty/guides/query/QueryEndpointIT.java`
----

QueryEndpointIT.java
[source, java, linenums, role="code_column hide_tags=copyright"]
----
include::finish/query/src/test/java/it/io/openliberty/guides/query/QueryEndpointIT.java[]
----

// file 1
query/pom.xml
[source, XML, linenums, role='code_column']
----
include::finish/query/pom.xml[]
----

The test code needs to know the information about the `system` service according to the activating profile to make requests. This information is stored as [hotspot=systemPropertyVariables file=1]`systemPropertyVariables` in the [hotspot file=1]`pom.xml` file. 

Each test case tests one of the endpoints of the `query` service.
The tests for `query` verify that the service can communicate with `system` using the configured properties. If the properties are misconfigured, then the `query` test fails.

=== Running the tests

Because you started Open Liberty in dev mode, you can run the tests by pressing the enter/return key from the command-line session where you started the `query` service.

[source, role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.query.QueryEndpointIT
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.542 s - in it.io.openliberty.guides.query.QueryEndpointIT
 
Results:
 
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0
----

When you are done checking out the service in `development` environment, stop the Open Liberty server by pressing `CTRL+C` in the command-line sessions where you ran the `query` and `system` services. 

You can also run tests against the `testing` profile from the `system` service.

Navigate to the `start` directory and start the `system` service in `testing` environment by running the following Maven goal:

[role='command']
```
mvn -pl system liberty:start
```

// file 0
[role="code_command hotspot file=0", subs="quotes"]
----
#Replace the `microprofile-config.properties` file.#
`query/src/main/resources/META-INF/microprofile-config.properties`
----

microprofile-config.properties
[source, properties, linenums, role="code_column hide_tags=copyright"]
----
include::finish/query/src/main/resources/META-INF/microprofile-config.properties[]
----

Start the `query` service and run the integration tests by running the following Maven goals:

[role='command']
```
mvn -pl query liberty:start
mvn -pl query failsafe:integration-test
```

[source, role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.query.QueryEndpointIT
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.542 s - in it.io.openliberty.guides.query.QueryEndpointIT
 
Results:
 
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0
----

After you are finished checking out the application, stop the Open Liberty server by running the following Maven goals:

[role='command']
```
mvn -pl system liberty:stop
mvn -pl query liberty:stop
```

== Great work! You're done!

You just learnt how to use Microfile Config Profile to configure the application for multiple environments.

Feel free to try one of the related guides. They demonstrate new technologies that you can learn and expand on top what you built in this guide.

include::{common-includes}/attribution.adoc[subs="attributes"]