// Copyright (c) 2022 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//   IBM Corporation
:projectid: microprofile-config-profile
:page-layout: guide-multipane
:page-duration: 30 minutes
:page-releasedate: 2022-12-09
:page-description: Explore how to externalize configuration using MicroProfile Config and configure microservices for different environments with MicroProfile Config Profile.
:page-tags: ['MicroProfile']
:page-permalink: /guides/{projectid}
:page-related-guides: ['microprofile-config-intro']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/prod
:source-highlighter: prettify
:page-seo-title: Configuring microservices for different environments with MicroProfile Config Profile
:page-seo-description: A tutorial and example on how to externalize configuration properties and configure multiple development stages for Java microservices using Eclipse MicroProfile Config.
:guide-author: Open Liberty
= Configuring microservices for different environments with MicroProfile Config Profile

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Explore how to externalize configuration using MicroProfile Config and configure microservices for different environments with MicroProfile Config Profile.

// =================================================================================================
// What you'll learn
// =================================================================================================
== What you'll learn
You will learn how to configure multiple environments by providing specific set of configuration properties for each environment with Config Profile. You will also explore the features to externalize your microservice's configuration properties.

// add more

// The two microservices you will be working with are called `system` and `query`. The system microservice returns the JVM system properties of the running container and it returns the pod’s name in the HTTP header making replicas easy to distinguish from each other. The inventory microservice adds the properties from the system microservice to the inventory. This process demonstrates how communication can be established between pods inside a cluster.

// =================================================================================================
// Getting Started
// =================================================================================================

[role=command]
include::{common-includes}/gitclone.adoc[]

// =================================================================================================
// Trying the application
// =================================================================================================
== Trying the application

// file 0
system/server.xml
[source, XML, linenums, role='code_column']
----
include::start/system/src/main/liberty/config/server.xml[]
----

// file 1
microprofile-config.properties
[source, Properties, linenums, role='code_column']
----
include::start/query/src/main/resources/META-INF/microprofile-config.properties[]
----

// file 2
system/pom.xml
[source, XML, linenums, role='code_column']
----
include::start/system/pom.xml[]
----

The starting Java project, which you can find in the `start` directory, is a multi-module Maven project that's made up of the `system` and `query` microservices. Each microservice resides in its own directory, `start/system` and `start/query`. 

The `system` microservice contains the two build profiles: `testing` and `development`. To start the `system` service in the `testing` configuration, navigate to the `start/system` directory and run the following Maven goal to build the service and deploy it to Open Liberty:

[role='command']
```
mvn -P testing liberty:run
```

In the `testing` profile, the deafult application configuration from the `server.xml` file is used. You can find out from the [hotspot file=0]`src/main/liberty/config/server.xml` file that the `system` service is running on the port [hotspot=port file=0]`9080` with the [hotspot=context.root file=0]`system` context root. It also uses the username [hotspot=username file=0]`bob` and the password [hotspot=password file=0]`bobpwd` as the authorized access to the resources from other services.

Next, open another command-line session and navigate to the `start/query` directory. 

When you run Open Liberty in development mode, known as dev mode, the server listens for file changes and automatically recompiles and deploys your updates whenever you save a new change. Run the following commands to start the `query` service in dev mode:

[role='command']
```
mvn liberty:dev
```

After you see the following message, your application server in dev mode is ready:

[source, role="no_copy"]
----
**************************************************
*     Liberty is running in dev mode.
----

Dev mode holds your command-line session to listen for file changes. Open another command-line session to continue, or open the project in your editor.

Access the [hotspot file=1]`src/main/resources/META-INF/microprofile-config.properties` local configuration file to check some static configuration. This configuration file is the default configuration source for an application that uses MicroProfile Config. Each property that has already been defined in this file configure the properties required to access `system` service.

Point your browser to the http://localhost:9085/query/systems/localhost URL and use the username `bob` and the password `bobpwd` to authenticate. The URL retrieves the system property information for the `localhost` host name by making a request to the `system` service.

After you are finished checking out the application, stop the `system` service by pressing `CTRL+C` in the command-line session where you ran the server. Alternatively, you can run the `liberty:stop` goal from the `start/system` directory in another shell session:

[role='command']
```
mvn liberty:stop
```

Then, restart the `system` service with the `development` profile by running the following Maven goal from the `start/system` directory:

[role='command']
```
mvn -P development liberty:run
```

// https://maven.apache.org/surefire/maven-failsafe-plugin/examples/system-properties.html
Now, the [hotspot=development file=2]`development` configuration overrides the default configuration values from the `server.xml` file.

You can find out from the `pom.xml` file that the `system` service now is running on the port [hotspot=port file=2]`9081` with the [hotspot=context.root file=2]`system/dev` context root. Moreover, you now need to use the new username, [hotspot=username file=2]`alice`, and the new password, [hotspot=password file=2]`wonderland`, to log in.

// =================================================================================================
// Adding configuration profile
// =================================================================================================
== Adding configuration profile

// file 0
microprofile-config.properties
[source, Properties, linenums, role='code_column']
----
include::start/query/src/main/resources/META-INF/microprofile-config.properties[]
----

Config Profiles allow configuration for different environments and development stages such as dev, testing, prod, etc. while only a single profile is active. The active Config Profile is specified via the property `mp.config.profile`, which can be set in any of the configuration sources or at application startup. Once it is set, the corresponding set of configuration properties associated with the active profile are used. 

Navigate to the [hotspot file=0]`query/src/main/resources/META-INF/microprofile-config.properties` local configuration file to check some static configuration. The value of each currently stored configuration property maps to the required value to access the `testing` configuration of the `system` service whilst the service is started with the `development` configuration.

Try to access the http://localhost:9085/query/systems/localhost URL. You can expect to see the following error message: `{"fail":"Failed to reach the client localhost."}`.

=== Creating configuration profile in properties level

A configuration property can be used at the property level by setting its name in the format: `%<mp.config.profile>.<original property name>`. 

[role="code_command hotspot file=0", subs="quotes"]
----
#Replace the `microprofile-config.properties` file.#
`query/src/main/resources/META-INF/microprofile-config.properties`
----

// file 0
microprofile-config.properties
[source, properties, linenums, role="code_column"]
----
include::staging/query/src/main/resources/META-INF/microprofile-config.properties[]
----

Configure the [hotspot=development file=0]`%development.*` properties with the value of the system property variables from the `development` profile of the `system` service.

Next, stop the `query` service by pressing `CTRL+C` in the command-line session where you ran the server, or by typing `q` and then pressing the `enter/return` key.

Then, restart the `query` service with the `development` configuration profile by running the following Maven goal from the `start/query` directory:

[role='command']
```
mvn liberty:dev -Dliberty.var.mp.config.profile="development"
```

With `mp.config.profile` set to `development`, each `%development.*` property overrides the value of its original property. For example, the property [hotspot=dev.port file=0]`%development.system.httpPort` overrides the property [hotspot=port file=0]`system.httpPort` and the value is resolved to `9081`.

Now, you can access the application by the http://localhost:9085/query/systems/localhost URL. 

=== Creating configuration profile using ConfigSource

Configuration properties can also be used at the ConfigSource level. Multiple config sources can be provided with the name formatted as `microprofile-config-<mp.config.profile>.properties` under the `META-INF` folder on the classpath so they can be used for specific selected profiles.

// file 0
[role="code_command hotspot file=0", subs="quotes"]
----
#Create the `microprofile-config-development.properties` file.#
`query/src/main/resources/META-INF/microprofile-config-development.properties`
----

microprofile-config-development.properties
[source, properties, linenums, role="code_column hide_tags=userPassword,properties,contactEmail,roleAndQuery"]
----
include::finish/query/src/main/resources/META-INF/microprofile-config-development.properties[]
----

Define the [hotspot=system file=0]`system.*` properties with the system property variables from the `development` configuration of the `system` service.

To use the configuration properties in [hotspot file=0]`microprofile-config-development.properties`,

// file 1
[role="code_command hotspot file=1", subs="quotes"]
----
#Replace the `microprofile-config.properties` file.#
`src/main/resources/META-INF/microprofile-config.properties`
----

microprofile-config.properties
[source, properties, linenums, role="code_column hide_tags=development"]
----
include::staging/query/src/main/resources/META-INF/microprofile-config.properties[]
----

Remove all the `%development.*` properties from the [hotspot file=1]`microprofile-config.properties` file.

Because the `mp.config.profile` is set to `development`, the file [hotspot file=0]`microprofile-config-development.properties` is loaded on top of the default [hotspot file=1]`microprofile-config.properties` file. The [hotspot=system file=0]`system.*` properties from [hotspot file=0]`microprofile-config-development.properties` thus take precedence.

Because you are running the `query` service in dev mode, the changes that you made were automatically picked up. You're now ready to check out your application in your browser.

Point your browser to the http://localhost:9085/query/systems/localhost URL to test out the application again. Your java version and operating system name is displayed.

// =================================================================================================
// Defining property with expressions
// =================================================================================================
== Defining property with expressions

The value of a config property may contain an expression corresponding to another config property. Property expressions provide a way to embed expression segments in property values using the `${}` sequence.

Additionally, you can also implement expressions with the following syntax:

* `${prop:default}` - Provides a `default` value after the `:` if the expression doesn't find a value for the property `prop`.

* `${prop${compose}}` - Composed expressions where inner expressions are resolved first.

* `${prop1}${prop2}` - Multiple expressions.

// file 0
[role="code_command hotspot file=0", subs="quotes"]
----
#Replace the `microprofile-config-development.properties` file.#
`query/src/main/resources/META-INF/microprofile-config-development.properties`
----

microprofile-config-development.properties
[source, properties, linenums, role="code_column hide_tags=properties,contactEmail"]
----
include::finish/query/src/main/resources/META-INF/microprofile-config-development.properties[]
----

Add the [hotspot=userPassword file=0]`system.userPassword` configuration property that is constructed by property [hotspot=user file=0]`system.user` and property [hotspot=password file=0]`system.password` to the `microprofile-config-development.properties` file.

The property [hotspot=userPassword file=0]`system.userPassword` is expanded to `alice:alicepwd`.

To use this configuration property,

// file 1
[role="code_command hotspot file=1", subs="quotes"]
----
#Replace the `SystemResource` class.#
`src/main/java/io/openliberty/guides/query/SystemResource.java`
----

SystemResource.java
[source, java, linenums, role="code_column hide_tags=copyright"]
----
include::staging/query/src/main/java/io/openliberty/guides/query/SystemResource.java[]
----

Replace the injection of the `system.user` and `system.password` configuration properties with the [hotspot=userPassword file=1]`system.userPassword` property, and use the value of [hotspot=authHeader file=1]`systemUserPassword` to construct the authorization header.

Because you are running the `query` service in dev mode, the changes that you made were automatically picked up.

Check out the service that you created at the http://localhost:9085/query/systems/localhost URL. If successful, it returns [] to you.

run the url http://localhost:9085/query/systems/localhost and success

// ===========================================================================================
== Retrieving property as a list

TBA...

// File 0
// Replace microprofile-config-development.properties
[role="code_command hotspot file=0", subs="quotes"]
----
#Replace the `microprofile-config-development.properties` file.#
`src/main/resources/META-INF/microprofile-config-development.properties`
----

microprofile-config-development.properties
[source, properties, linenums, role="code_column hide_tags=roleAndQuery"]
----
include::finish/query/src/main/resources/META-INF/microprofile-config-development.properties[]
----

add the [hotspot=properties file=0]`system.properties` property that contains a list of property names seperated by comma.

// File 1
// Replace SystemResource.java
[role="code_command hotspot file=1", subs="quotes"]
----
#Replace the `SystemResource` class.#
`src/main/java/io/openliberty/guides/query/SystemResource.java`
----

SystemResource.java
[source, java, linenums, role="code_column hide_tags=copyright"]
----
include::finish/query/src/main/java/io/openliberty/guides/query/SystemResource.java[]
----

Add the [hotspot=systemPropertiesProperty file=1]`system.properties` configuration property that is defined with `List<String>` type.

Iterate through the [hotspot=systemProperties file=1]`systemProperties` list to retreve all property values by calling the `systemClient` REST client.

run the url http://localhost:9085/query/systems/localhost and see more properties.

// ===========================================================================================
== Using configuration source APIs

TBA...

// File 0
// Replace microprofile-config-development.properties
[role="code_command hotspot file=0", subs="quotes"]
----
#Replace the `microprofile-config-development.properties` file.#
`src/main/resources/META-INF/microprofile-config-development.properties`
----

microprofile-config-development.properties
[source, properties, linenums, role="code_column"]
----
include::finish/query/src/main/resources/META-INF/microprofile-config-development.properties[]
----

add the [hotspot=roleAndQuery file=0]`role` and [hotspot=roleAndQuery file=0]`query.*` properties.

The [hotspot=contactEmail file=0]`query.contactEmail` property specifies `admin` as the default value, and uses composed expression where the `${role}` inner expressions is resolved first.

// File 1
// Create ConfigResource.java
[role="code_command hotspot file=1", subs="quotes"]
----
#Create the `ConfigResource` class.#
`src/main/java/io/openliberty/guides/query/ConfigResource.java`
----

ConfigResource.java
[source, java, linenums, role="code_column hide_tags=copyright,systemConfig,getSystemConfig"]
----
include::finish/query/src/main/java/io/openliberty/guides/query/ConfigResource.java[]
----

Explain different APIs, e.g [hotspot=config file=1]`Config` class provides..., [hotspot=configValue file=1]`ConfigValue` claass provides..., ...

run the urls http://localhost:9085/query/config and http://localhost:9085/query/config/contact

// ===========================================================================================
== Aggregating configuration properties into a CDI bean

TBA...

// File 0
// Create ConfigSystemBean.java
[role="code_command hotspot file=0", subs="quotes"]
----
#Create the `ConfigSystemBean` class.#
`src/main/java/io/openliberty/guides/query/ConfigSystemBean.java`
----

ConfigSystemBean.java
[source, properties, linenums, role="code_column hide_tags=copyright"]
----
include::finish/query/src/main/java/io/openliberty/guides/query/ConfigSystemBean.java[]
----

Annotate the `ConfigSystemBean` class by [hotspot=prefix file=0]`@ConfigProperties` annotation with setting the `prefix` attribute to `system`... 

and more...

// File 1
// Replace ConfigResource.java
[role="code_command hotspot file=1", subs="quotes"]
----
#Replace the `ConfigResource` class.#
`src/main/java/io/openliberty/guides/query/ConfigResource.java`
----

ConfigResource.java
[source, java, linenums, role="code_column hide_tags=copyright"]
----
include::finish/query/src/main/java/io/openliberty/guides/query/ConfigResource.java[]
----

Inject the [hotspot=systemConfig file=1]`systemConfig` field variable ... ,

Add the [hotspot=getSystemConfig file=1]`/query/config/system` endpoint ...

run url http://localhost:9085/query/config/system


// ===========================================================================================
== Testing the application

TBA...

== Great work! You're done!

You just learnt how to use Microfile Config Profile to configure the application for multiple environments.

Feel free to try one of the related guides. They demonstrate new technologies that you can learn and expand on top what you built in this guide.

include::{common-includes}/attribution.adoc[subs="attributes"]