// Copyright (c) 2023 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//   IBM Corporation
:projectid: microprofile-config-apis
:page-layout: guide-multipane
:page-duration: 25 minutes
:page-releasedate: 2023-01-31
:page-description: Learn how to use MicroProfile Config APIs to access and aggregate configuration properties.
:page-tags: ['MicroProfile']
:page-permalink: /guides/{projectid}
:page-related-guides: ['microprofile-config-intro', 'microprofile-config-profile']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/prod
:source-highlighter: prettify
:page-seo-title: Aggregating Java microservices configuration with different properties using MicroProfile Config APIs
:page-seo-description: A tutorial and example on how to access configuration details and aggregate configuration properties into a CDI bean for Java microservices using MicroProfile Config APIs.
:guide-author: Open Liberty
= Aggregating configuration properties

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Learn how to use MicroProfile Config APIs to access configuration details and aggregate configuration properties into a CDI bean.

:win: WINDOWS
:mac: MAC
:linux: LINUX

// =================================================================================================
// What you'll learn
// =================================================================================================
== What you'll learn

You'll learn how to ... (need to write up). This guide assumes you are familiar with https://openliberty.io/docs/latest/external-configuration.html[External configuration of microservices^] and  https://openliberty.io/docs/latest/reference/feature/mpConfig-3.0.html[MicroProfile Config^]. If you're new to MicroProfile Config, you might want to start with the https://openliberty.io/guides/microprofile-config-intro.html[Separating configuration from code in microservices^] guide and the https://openliberty.io/guides/microprofile-config.html[Configuring microservices^] guide first.

The application that you will be working with is a `query` service. It fetches properties from the `system` microservice. You'll learn different ways to retreive configuration for the `system` service using MicroProfile Config APIs.

// =================================================================================================
// Getting Started
// =================================================================================================

[role=command]
include::{common-includes}/gitclone.adoc[]

// =================================================================================================
=== Try what youll build

The `finish` directory contains the finished implementation for the services in the application. Try the finished application before you build your own.

To try out the application, run the following commands to navigate to the `finish/system` directory and deploy the `system` service to Open Liberty:

[role='command']
```
cd finish/system
mvn liberty:run
```

Open another command-line session and run the following commands to navigate to the `finish/query` directory and deploy the `query` service to Open Liberty:

[role='command']
```
cd finish/query
mvn liberty:run
```

After you see the following message in both command-line sessions, both of your services are ready:

[source, role="no_copy"]
----
The defaultServer server is ready to run a smarter planet.
----

Point your browser to the following URLs:

* http://localhost:9085/query/systems/localhost URL returns the current OS and Java properties in JSON format. The URL retrieves the system property information for the `localhost` hostname by making a request to the `system` service at `\http://localhost:<system.httpPort>/<system.contextRoot>/property/{property}`. 

* http://localhost:9085/query/config/contact URL returns the source name, source ordinal, and value of the `query.contactEmail` property.

* http://localhost:9085/query/config URL returns all registered configuration sources and properties of the running `query` service.

* http://localhost:9085/query/config/system URL returns all the configuration properties prefixed with `system.`

After you are finished checking out the application, leave the `system` service running and stop the `query` service by pressing `CTRL+C` in the command-line sessions where you ran the `query` service. Alternatively, you can run the following goals from the `finish/query` directory in another command-line session:

[role='command']
```
mvn -pl liberty:stop
```

// =================================================================================================
== Defining property with expressions

// static guide instructions:
ifndef::cloud-hosted[]
Now, navigate to the `start` directory to begin.
endif::[]

// cloud-hosted guide instructions:
ifdef::cloud-hosted[]
To begin, run the following command to navigate to the **start** directory:
```bash
cd /home/project/guide-microprofile-config-apis/start
```
endif::[]

When you run Open Liberty in development mode, known as dev mode, the server listens for file changes and automatically recompiles and deploys your updates whenever you save a new change. Run the following commands to navigate to the `query` directory and start the `query` service in dev mode:

[role='command']
```
cd query
mvn liberty:dev
```

// file 0
system/server.xml
[source, XML, linenums, role='code_column']
----
include::finish/system/src/main/liberty/config/server.xml[]
----

// file 1
query/SystemResource.java
[source, XML, linenums, role='code_column']
----
include::start/query/src/main/java/io/openliberty/guides/query/SystemResource.java[]
----

A [hotspot=basicRegistry file=0]`basicRegistry` element is configured in the `system` microservice. Only the registered user is authorized to access to the `system` microservice. Note that this `basicRegistry` element is a very simple case for learning purposes. For more information about the different user registries, see the https://openliberty.io/docs/latest/user-registries-application-security.html[User registries documentation^].

The `/query/systems/{hostname}` endpoint constructs the [hotspot=authHeader file=1]`authHeader` authorization header with the [hotspot=user file=1]`system.user` and [hotspot=password file=1]`system.password` properties for accessing the `system` microservice. 

Point your browser to the http://localhost:9085/query/systems/localhost URL. You are expected to see the current OS name and Java version in JSON format. 

Property expressions provide a way to embed expression segments in property values by using the `${...}` sequence. You can include the value of a configuration property in another configuration property by using the `${prop}` syntax. Additionally, you can implement expressions with the following syntax:

* `${prop:default}` - Provides a `default` value after the `:` character if the expression doesn't find a value for the `prop` property.

* `${prop${compose}}` - Composed expressions where inner expressions are resolved first.

* `${prop1}${prop2}` - Multiple expressions.

// file 2
[role="code_command hotspot file=2", subs="quotes"]
----
#Replace the `microprofile-config.properties` file.#
`query/src/main/resources/META-INF/microprofile-config.properties`
----

query/microprofile-config.properties
[source, properties, linenums, role="code_column hide_tags=properties,roleAndQuery"]
----
include::finish/query/src/main/resources/META-INF/microprofile-config.properties[]
----

Add the [hotspot=userPassword file=2]`system.userPassword` configuration property to the `microprofile-config.properties` file. The [hotspot=userPassword file=2]`system.userPassword` property is expanded to `alice:alicepwd`.

// file 3
[role="code_command hotspot file=3", subs="quotes"]
----
#Replace the `SystemResource` class.#
`query/src/main/java/io/openliberty/guides/query/SystemResource.java`
----

query/SystemResource.java
[source, java, linenums, role="code_column hide_tags=copyright"]
----
include::staging/query/src/main/java/io/openliberty/guides/query/SystemResource.java[]
----

Replace the injection of the `system.user` and `system.password` properties with the [hotspot=userPassword file=3]`system.userPassword` property, and use the [hotspot=authHeader file=3]`systemUserPassword` variable to construct the authorization header.

Because you are running the `query` service in dev mode, the changes that you made were automatically picked up. Check out the service that you modified at the http://localhost:9085/query/systems/localhost URL.

// ===========================================================================================
== Retrieving property as a list

Configuration values are purely Strings. MicroProfile Config API has built-in converters that automatically converts configured Strings into target types and retrieves multi-valued properties as lists.

// file 0
[role="code_command hotspot file=0", subs="quotes"]
----
#Replace the `microprofile-config.properties` file.#
`query/src/main/resources/META-INF/microprofile-config.properties`
----

query/microprofile-config.properties
[source, properties, linenums, role="code_column hide_tags=roleAndQuery"]
----
include::finish/query/src/main/resources/META-INF/microprofile-config.properties[]
----

Add the [hotspot=properties file=0]`system.properties` property that contains a list of system properties that are separated by commas.

Next, update the `/query/systems/{hostname}` endpoint to list more system properties.

// file 1
[role="code_command hotspot file=1", subs="quotes"]
----
#Replace the `SystemResource` class.#
`query/src/main/java/io/openliberty/guides/query/SystemResource.java`
----

query/SystemResource.java
[source, java, linenums, role="code_column hide_tags=copyright"]
----
include::finish/query/src/main/java/io/openliberty/guides/query/SystemResource.java[]
----

Inject the [hotspot=systemPropertiesProperty file=1]`system.properties` configuration property as a `List<String>` type.

Then, modify the [hotspot=getSystemPropertiesMethod file=1]`getSystemProperties()` method. Iterate through the [hotspot=systemProperties file=1]`systemProperties` list to retrieve all the specified property values from the `systemClient` REST client.

Check out the service that you modified at the http://localhost:9085/query/systems/localhost URL. You see a result in JSON format with the specified system properties in JSON format.

// ===========================================================================================
== Using configuration source APIs

MicroProfile Config provides configuration source https://openliberty.io/docs/latest/reference/javadoc/microprofile-5.0-javadoc.html?package=org/eclipse/microprofile/config/package-frame.html&class=org/eclipse/microprofile/config/package-summary.html[APIs^] for retrieving details about configuration properties. You can use the `ConfigValue` API class to retrieve various useful information about a single specified configuration property. Alternatively, you can use the `Config` API class to look up the metadata of all underlying configuration properties. 

You will implement endpoints that retrieve information specific to this guide by using the two API classes.

// file 0
[role="code_command hotspot file=0", subs="quotes"]
----
#Replace the `microprofile-config.properties` file.#
`query/src/main/resources/META-INF/microprofile-config.properties`
----

query/microprofile-config.properties
[source, properties, linenums, role="code_column"]
----
include::finish/query/src/main/resources/META-INF/microprofile-config.properties[]
----

Add the [hotspot=role file=0]`role` and the [hotspot=query file=0]`query.*` properties. The [hotspot=contactEmail file=0]`query.contactEmail` property contains composed property expression where the `${role}` inner expression is expanded first. The `${query.${role}}` expression provides the `admin` default value if the expression doesn't find a value.


Implement the `/query/config` and `/query/config/contact` endpoints in the `query` service to retrieve configuration information by MicroProfile Config APIs.
 
// file 1
[role="code_command hotspot file=1", subs="quotes"]
----
#Create the `ConfigResource` class.#
`query/src/main/java/io/openliberty/guides/query/ConfigResource.java`
----

query/ConfigResource.java
[source, java, linenums, role="code_column hide_tags=copyright,systemConfig,getSystemConfig"]
----
include::finish/query/src/main/java/io/openliberty/guides/query/ConfigResource.java[]
----

Inject the [hotspot=contactEmail file=1]`query.contactEmail` property as usual, only this time define the type as `ConfigValue`. 

The [hotspot=configValue file=1]`ConfigValue` metadata object holds additional information after the lookup of the [hotspot=queryContactEmail file=1]`query.contactEmail` property. The [hotspot=getSourceName file=1]`getSourceName()` method determines which ConfigSource has the highest ordinal for the specified property. The [hotspot=getSourceOrdinal file=1]`getSourceOrdinal()` method returns the ordinal value of the ConfigSource that loaded the property lookup. The [hotspot=getValue file=1]`getValue()` methods returns the value of the specified property.

Inject the [hotspot=config file=1]`Config` metadata object. You can use it to resolve the property value by searching through all configured ConfigSources.

The [hotspot=getConfigSources file=1]`getConfigSources()` method returns all the registered configuration sources for the running service. The [hotspot=getPropertyNames file=1]`getPropertyNames()` method finds all configuration property names by searching through all the registered ConfigSources.

Check out the following endpoints that you created:

* http://localhost:9085/query/config/contact returns the source name, source ordinal, and value of the `query.contactEmail` property.

* http://localhost:9085/query/config returns all registered configuration sources and properties of the running `query` service.

// ===========================================================================================
== Aggregating configuration properties into a CDI bean

Microprofile Config provides a way to aggregate configuration properties that start with the same prefix into a single property class through the `@ConfigProperties` annotation.

Define a CDI bean for the configuration properties that share the common prefix `system.`.

// file 0
[role="code_command hotspot file=0", subs="quotes"]
----
#Create the `ConfigSystemBean` class.#
`query/src/main/java/io/openliberty/guides/query/ConfigSystemBean.java`
----

query/ConfigSystemBean.java
[source, java, linenums, role="code_column hide_tags=copyright"]
----
include::finish/query/src/main/java/io/openliberty/guides/query/ConfigSystemBean.java[]
----

Annotate the [hotspot=ConfigSystemBean file=0]`ConfigSystemBean` class with the [hotspot=prefix file=0]`@ConfigProperties` annotation. The [hotspot=prefix file=0]`prefix` attribute specifies the common prefix of the configuration properties to `system`.


Use the `ConfigSystemBean` class in the `ConfigResource` class.

// file 1
[role="code_command hotspot file=1", subs="quotes"]
----
#Replace the `ConfigResource` class.#
`query/src/main/java/io/openliberty/guides/query/ConfigResource.java`
----

query/ConfigResource.java
[source, java, linenums, role="code_column hide_tags=copyright"]
----
include::finish/query/src/main/java/io/openliberty/guides/query/ConfigResource.java[]
----

The [hotspot=inject file=1]`@Inject` and [hotspot=ConfigProperties file=1]`@ConfigProperties` annotations inject the `ConfigSystemBean` CDI bean to the [hotspot=systemConfig file=1]`systemConfig` field variable.

The [hotspot=getSystemConfig file=1]`getSystemConfig()` method implements the `/query/config/system` endpoint. The endpoint uses the [hotspot=configSystemBean file=1]`systemConfig` bean to retrieve the values of the [hotspot=systemProperties file=1]`system.*` configuration properties without having to inject them one by one.

Check out the endpoint that you created at the http://localhost:9085/query/config/system URL. You see all the configuration properties prefixed with `system.`.

// ===========================================================================================
== Implementing test cases

You will create endpoint tests to test the basic functionality of the `query` microservice. If a test failure occurs, then you might have introduced a bug into the code.

// file 0
[role="code_command hotspot file=0", subs="quotes"]
----
#Create the `QueryEndpointIT` class.#
`query/src/test/java/it/io/openliberty/guides/query/QueryEndpointIT.java`
----

QueryEndpointIT.java
[source, java, linenums, role="code_column hide_tags=copyright"]
----
include::finish/query/src/test/java/it/io/openliberty/guides/query/QueryEndpointIT.java[]
----

// file 1
query/pom.xml
[source, XML, linenums, role='code_column']
----
include::finish/query/pom.xml[]
----

See the following descriptions of the test cases:

* [hotspot=testQuerySystem file=0]`testQuerySystem()` verifies the `/query/systems/{hostname}` endpoint.

* [hotspot=testQueryConfigContact file=0]`testQueryConfigContact()` verifies the `/query/config/contact` endpoint.

* [hotspot=testQueryConfig file=0]`testQueryConfig()` verifies the `/query/config` endpoint.

* [hotspot=testQueryConfigSystem file=0]`testQueryConfigSystem()` verifies the `/query/config/system` endpoint.

* [hotspot=testUnknownHost file=0]`testUnknownHost()` verifies that an unknown host or a host that does not expose their JVM system properties is correctly handled with a fail message.

**Running the tests**

Because you started Open Liberty in dev mode, you can run the tests by pressing the enter/return key from the command-line session where you started the `query` service. If the tests pass, you see a similar output to the following example:

[source, role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.query.QueryEndpointIT
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.703 s - in it.io.openliberty.guides.query.QueryEndpointIT

Results:

Tests run: 5, Failures: 0, Errors: 0, Skipped: 0
----

When you are done checking out the application, exit dev mode by pressing `CTRL+C` in the command-line sessions where you ran the `system` and `query` services, or by typing `q` and then pressing the `enter/return` key. Alternatively, you can run the `liberty:stop` goal from the `start` directory in another command-line session for the `system` and `query` services:
// static guide instruction
ifndef::cloud-hosted[]
[role="command"]
----
mvn -pl system liberty:stop
mvn -pl query liberty:stop
----
endif::[]
// cloud hosted instruction
ifdef::cloud-hosted[]
```bash
cd /home/project/guide-microprofile-config-profile/start
mvn -pl system liberty:stop
mvn -pl backendServices liberty:stop
```
endif::[]

== Great work! You're done!

You just learnt how to use Microfile Config APIs to aggregate configuration properties into a CDI bean.

Feel free to try one of the related guides. They demonstrate new technologies that you can learn and expand on top what you built in this guide.

include::{common-includes}/attribution.adoc[subs="attributes"]